  /*
   * TODO: Implement pipeline stages/steps
   *   See documentation: https://www.jenkins.io/doc/book/pipeline/syntax/#stages
   */
pipeline {
             stage('Build with Gradle') {
                 steps {
                     sh './gradlew assemble'
                 }
             }

             stage('Test with Gradle') {
                 steps {
                     sh './gradlew test'
                 }
             }
         }
     }